# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/configuration-reference
version: 2.1
jobs:
  build:
    docker:
      - image: docker:20.10.9
    steps:
      - checkout
      - run:
          name: Build project with Docker
          command: |
            docker build -t antoniomassa83/finalproject:command .
            docker push antoniomassa83/finalproject:command


