# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/configuration-reference
version: 2.1
jobs:
  build:
    working_directory: /app
    docker:
      - image: docker:20.10.7
    steps:
      - checkout
      - run:
          name: Install Maven
          command: |
            apk add --no-cache openjdk11 maven
      - run:
          name: Build and test
          command: |
            mvn clean package
            docker build -t antoniomassa83/finalproject:command .
      - run:
          name: Push to Docker Hub
          command: |
            echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
            docker push antoniomassa83/finalproject:command
          
workflows:
  version: 2.1
  build_and_test:
    jobs:
      - build

