version: 2.1

jobs:
  build:
    docker:
      - image: cimg/openjdk:15.0
    working_directory: command
    steps:
      - setup_remote_docker:
          docker_layer_caching: true
      - checkout
      - run:
          name: Build Docker Image
          command: |
            docker build -t antoniomassa83/finalproject:command .
            docker push antoniomassa83/finalproject:command
      - run:
          name: Run JUnit Tests and collect coverage
          command: |
            docker run --rm \
              -v `pwd`:/app \
              -w /app \
              antoniomassa83/finalproject:command \
              sh -c "./gradlew test jacocoTestReport"
      - store_test_results:
          path: build/test-results
      - store_artifacts:
          path: "build/reports/jacoco"
          destination: "jacoco"
  deploy:
    docker:
      - image: cimg/openjdk:15.0
    working_directory: command
    steps:
      - checkout
      - run:
          name: Deploy to Production
          command: |
            docker pull antoniomassa83/finalproject:command
            docker stop finalproject || true
            docker rm finalproject || true
            docker run -d --name finalproject -p 8080:8080 antoniomassa83/finalproject:command

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master
