# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/configuration-reference
version: 2.1
orbs:
  docker: circleci/docker@1.7.0

# Define a job to be invoked later in a workflow.
# See: https://circleci.com/docs/configuration-reference/#jobs
jobs:
  build-and-push:
    # Specify the execution environment
    docker:
      - image: cimg/base:stable
    # Add steps to the job
    steps:
      - checkout
      - run:
          name: "Build Docker image"
          command: "docker build -t command ."
      - run:
          name: "Tag Docker image"
          command: "docker tag command my-registry/command:${CIRCLE_SHA1}"
      - run:
          name: "Login to Docker registry"
          command: "echo $DOCKER_REGISTRY_PASSWORD | docker login -u $DOCKER_REGISTRY_USERNAME --password-stdin my-registry"
      - run:
          name: "Push Docker image"
          command: "docker push my-registry/command:${CIRCLE_SHA1}"

# Orchestrate jobs using workflows
# See: https://circleci.com/docs/configuration-reference/#workflows
workflows:
    example-workflow:
      jobs:
        - docker/publish:
            image: Command 
